server:
  error:
    include-message: always
    include-binding-errors: always
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/poll_me
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
